#%RAML 1.0 Trait
usage: Apply this trait to enforce client crendetials
description: Enable client-id enforcement authentication
headers:
  client_id:
    description: Client ID
    type: string
  client_secret:
    description: Client Secret
    type: string